version: "3"
services:
  zenbership:
    build: .
    image: php:7.0-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: zenbership
      MYSQL_PASSWORD: "NUgget38!@"
      MYSQL_USER: zenbership_user
      MYSQL_ROOT_PASSWORD: "NUgget38!@"
    networks:
      - zenbership-net
    depends_on:
      - mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:5.6.30
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: zenbership
      MYSQL_PASSWORD: "NUgget38!@"
      MYSQL_USER: zenbership_user
      MYSQL_ROOT_PASSWORD: "NUgget38!@"
    networks:
      - zenbership-net
    command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION
    deploy:
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8091:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - zenbership-net
networks:
  zenbership-net:
