version: "3"
services:
  shulnet:
    build: .
    image: "parkerfly38/shulnet:shulnet-apache"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: shulnet
      MYSQL_PASSWORD: "shulnet"
      MYSQL_USER: shulnet_user
      MYSQL_ROOT_PASSWORD: "shulnetroot"
    networks:
      - shulnet-net
    depends_on:
      - mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      restart_policy:
        condition: on-failure
  mysql:
    image: "parkerfly38/shulnet:shulnet-mysql"
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: shulnet
      MYSQL_PASSWORD: "shulnet"
      MYSQL_USER: shulnet_user
      MYSQL_ROOT_PASSWORD: "shulnetroot"
    networks:
      - shulnet-net
    command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  shulnet-net:
